#      __  __      ____                        ______
#     / / / /_  __/ __ \________  ____ _____  / ____/___  ________
#    / /_/ / / / / / / / ___/ _ \/ __ `/ __ \/ /   / __ \/ ___/ _ \
#   / __  / /_/ / /_/ / /__/  __/ /_/ / / / / /___/ /_/ / /  /  __/
#  /_/ /_/\__, /\____/\___/\___/\__,_/_/ /_/\____/\____/_/   \___/
#        /____/
# By HyOceanDevelopmentTeam Composed By PaperTrain
-|: 'Project: ${project.artifactId}, Version: ${project.version}'

# Language
DefaultLang: IT # IT / EN

# Update Section
checkUpdates: true
bStats: true

# Location Section
Spawn:
  World: "WorldName"
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0

Parkour:
  World: "WorldName"
  X: 0
  Y: 0
  Z: 0
  Pitch: 0
  Yaw: 0


